services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: infra/docker/dockerfile
  #   ports:
  #     - 5001:3000
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/app
  #   working_dir: /app

  # db:
  #   image: postgres:15
  #   ports:
  #     - 5455:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=discus
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_NOTIFY_WEBHOOK_ENABLE_primary=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary=http://host.docker.internal:8000/storage/webhook
    command: server /data --console-address ":9001"
    volumes:
      - storage_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./scripts/init-minio.sh:/init-minio.sh
    entrypoint: /bin/sh
    command: -c "/init-minio.sh"


volumes:
  # db_data:
  storage_data: